### ISSUE TITLE
Issue In Save File Path Location In auto and manual options (WINDOWS version)

### ISSUE THREAD

**Issue by LYZENCORE-9** [HGStyle/GD-SaveFileFixer#2]
actually the program doing nothing in save file path (LOCALAPPDATA) if he find the save file path is corrupted

**Comment by LYZENCORE-9** [comment]
i can fix this but i have exams this days

**Comment by HGStyle** [comment]
could you explain a bit more please ?
anyways, i'm compilling the binaries for v2, maybe it'll be fixed since it's 80% rewritten

**Comment by HGStyle** [comment]
just released v2, could you check if the bug is still there please ?

**Comment by LYZENCORE-9** [comment]
> just released v2, could you check if the bug is still there please ?

i will check

**Comment by HGStyle** [comment]
Should be fixed as the methods to find savefiles have been rewrote in v2.
