### ISSUE TITLE
Does it work on IOS

### ISSUE THREAD

**Issue by ImmediateMurderProfessionals** [HGStyle/GD-SaveFileFixer#3]
My geometry dash account BombCraft2010 has been falsely disabled because a salty little crotch goblin (30IGeometryDash) mass reported my levels. All my 20K+ comments and 1.1K+ levels have been deleted from the servers. I want to make a new account, but if I log off of my account and create a new one, all my data will be gone, and I don’t want that because I have ~2K hours in GD (I have made six rateworthy levels and have beaten 89 demons). Could I use this repo on iOS and edit my save file so that I can have all my save data but on a different account?

**Comment by HGStyle** [comment]
@ImmediateMurderProfessionals In my README file, I point out a Reddit tuto on extracting the game data. Link is here:
https://www.reddit.com/r/geometrydash/comments/1ak4ssz/tutorial_how_to_access_the_game_files_get_nongs/

**Comment by ImmediateMurderProfessionals** [comment]
Ok
What’s an ipa file

**Comment by HGStyle** [comment]
> Ok What’s an ipa file

It's an APK but for iDevices. It contains the app to be installed when you use the file in the installer. For iDevices, there are no official installers, only unofficial ones such as Cydia Impactor (which is now pretty much useless unless you're an Apple certified developer) or pretty much anything you can find on Google and that is recommended (by the r/jailbreak community by example). On Android it's way simpler as there is only one installer and it's pre-installed (it's just called "Installer" but is hidden, to install an APK on Android you just need to click it via a file manager).

**Comment by ImmediateMurderProfessionals** [comment]
Ok
