### ISSUE TITLE
How exactly does it work

### ISSUE THREAD

**Issue by ImmediateMurderProfessionals** [HGStyle/GD-SaveFileFixer#4]
So I recently asked if it works on iOS. But now I’m wondering if I can do exactly what I want to do, which is:

Grab my save data
Edit CCGameManager.dat to be signed into my new account “BombCraftIsBack” rather than my old account “BombCraft2010”.
Edit CCLocalLevels.dat to set all my levels to verified so I can easily reupload my deleted levels
Replace my old save data with my new Dave data

This is super important, I have 2000 hours on gd and I don’t want to lose it all solely because some salty crotch goblin mass reported me

**Comment by ImmediateMurderProfessionals** [comment]
But it still may be hard cuz I play on iOS 17

**Comment by ImmediateMurderProfessionals** [comment]
(I think 17.5.1 to be exact)

**Comment by ImmediateMurderProfessionals** [comment]
Yup I am on 17.5.1

**Comment by ImmediateMurderProfessionals** [comment]
Hello?

**Comment by HGStyle** [comment]
Hi @ImmediateMurderProfessionals, I am sorry for my very late response. Anyways, from the moment you can grab your save files (which is possible, just look in the iOS section of the README for a link to a Reddit tutorial).
It'll be more easy if you have a PC (preferably a Windows one) so you could do this:
1. Use the tuto to grab the save files
2. Use a script to convert the Apple (iOS/MacOS) savefile to a Windows/Android savefile (I can do the script for you if needed)
3. Load the savefile in GD on Windows
4. Use GDHM or Geode mods to have verify hack and logout hack
5. Use logout hack to logout without losing data and login to your new account
6. Use verify hack to upload unverified levels

If you don't have a Windows PC, that's gonna be complicated. I can still help you, but honestly I don't read GitHub issues often, so I recommend you to join my Discord server and DM me (DM "{Owner} HGStyle"): https://dsc.gg/hgstyle

**Comment by ImmediateMurderProfessionals** [comment]
> Hi @ImmediateMurderProfessionals, I am sorry for my very late response. Anyways, from the moment you can grab your save files (which is possible, just look in the iOS section of the README for a link to a Reddit tutorial). It'll be more easy if you have a PC (preferably a Windows one) so you could do this:
> 
> 1. Use the tuto to grab the save files
> 2. Use a script to convert the Apple (iOS/MacOS) savefile to a Windows/Android savefile (I can do the script for you if needed)
> 3. Load the savefile in GD on Windows
> 4. Use GDHM or Geode mods to have verify hack and logout hack
> 5. Use logout hack to logout without losing data and login to your new account
> 6. Use verify hack to upload unverified levels
> 
> If you don't have a Windows PC, that's gonna be complicated. I can still help you, but honestly I don't read GitHub issues often, so I recommend you to join my Discord server and DM me (DM "{Owner} HGStyle"): https://dsc.gg/hgstyle

I do have a windows and in fact this comment was posted with my windows, but i do not have a copy of gd on my windows or a steam account.

**Comment by HGStyle** [comment]
> > Hi @ImmediateMurderProfessionals, I am sorry for my very late response. Anyways, from the moment you can grab your save files (which is possible, just look in the iOS section of the README for a link to a Reddit tutorial). It'll be more easy if you have a PC (preferably a Windows one) so you could do this:
> > 
> > 1. Use the tuto to grab the save files
> > 2. Use a script to convert the Apple (iOS/MacOS) savefile to a Windows/Android savefile (I can do the script for you if needed)
> > 3. Load the savefile in GD on Windows
> > 4. Use GDHM or Geode mods to have verify hack and logout hack
> > 5. Use logout hack to logout without losing data and login to your new account
> > 6. Use verify hack to upload unverified levels
> > 
> > If you don't have a Windows PC, that's gonna be complicated. I can still help you, but honestly I don't read GitHub issues often, so I recommend you to join my Discord server and DM me (DM "{Owner} HGStyle"): https://dsc.gg/hgstyle
> 
> I do have a windows and in fact this comment was posted with my windows, but i do not have a copy of gd on my windows or a steam account.

Okay, then just use a crack of Geometry Dash. That would be okay to use a crack just for data recovery :) If you need a good crack, go to SteamUnlocked's website and search Geometry Dash. (Use an AdBlocker as there's many ads on the download websites, althought it's possible without an AdBlocker it's just a bit harder)

**Comment by ImmediateMurderProfessionals** [comment]
> > > Hi @ImmediateMurderProfessionals, I am sorry for my very late response. Anyways, from the moment you can grab your save files (which is possible, just look in the iOS section of the README for a link to a Reddit tutorial). It'll be more easy if you have a PC (preferably a Windows one) so you could do this:
> > > 
> > > 1. Use the tuto to grab the save files
> > > 2. Use a script to convert the Apple (iOS/MacOS) savefile to a Windows/Android savefile (I can do the script for you if needed)
> > > 3. Load the savefile in GD on Windows
> > > 4. Use GDHM or Geode mods to have verify hack and logout hack
> > > 5. Use logout hack to logout without losing data and login to your new account
> > > 6. Use verify hack to upload unverified levels
> > > 
> > > If you don't have a Windows PC, that's gonna be complicated. I can still help you, but honestly I don't read GitHub issues often, so I recommend you to join my Discord server and DM me (DM "{Owner} HGStyle"): https://dsc.gg/hgstyle
> > 
> > 
> > I do have a windows and in fact this comment was posted with my windows, but i do not have a copy of gd on my windows or a steam account.
> 
> Okay, then just use a crack of Geometry Dash. That would be okay to use a crack just for data recovery :) If you need a good crack, go to SteamUnlocked's website and search Geometry Dash. (Use an AdBlocker as there's many ads on the download websites, althought it's possible without an AdBlocker it's just a bit harder)

okay. also why hasn't steamunlocked been dmcaed yet?

**Comment by HGStyle** [comment]
> > > > Hi @ImmediateMurderProfessionals, I am sorry for my very late response. Anyways, from the moment you can grab your save files (which is possible, just look in the iOS section of the README for a link to a Reddit tutorial). It'll be more easy if you have a PC (preferably a Windows one) so you could do this:
> > > > 
> > > > 1. Use the tuto to grab the save files
> > > > 2. Use a script to convert the Apple (iOS/MacOS) savefile to a Windows/Android savefile (I can do the script for you if needed)
> > > > 3. Load the savefile in GD on Windows
> > > > 4. Use GDHM or Geode mods to have verify hack and logout hack
> > > > 5. Use logout hack to logout without losing data and login to your new account
> > > > 6. Use verify hack to upload unverified levels
> > > > 
> > > > If you don't have a Windows PC, that's gonna be complicated. I can still help you, but honestly I don't read GitHub issues often, so I recommend you to join my Discord server and DM me (DM "{Owner} HGStyle"): https://dsc.gg/hgstyle
> > > 
> > > 
> > > I do have a windows and in fact this comment was posted with my windows, but i do not have a copy of gd on my windows or a steam account.
> > 
> > 
> > Okay, then just use a crack of Geometry Dash. That would be okay to use a crack just for data recovery :) If you need a good crack, go to SteamUnlocked's website and search Geometry Dash. (Use an AdBlocker as there's many ads on the download websites, althought it's possible without an AdBlocker it's just a bit harder)
> 
> okay. also why hasn't steamunlocked been dmcaed yet?

No idea, but it's probably like asking why isn't The Pirate Bay not dead yet, after dozens of years of service... SteamUblnlocked has been providing GD cracks since 1.9 but they're still here, standing strong...

**Comment by ImmediateMurderProfessionals** [comment]
> > > > > Hi @ImmediateMurderProfessionals, I am sorry for my very late response. Anyways, from the moment you can grab your save files (which is possible, just look in the iOS section of the README for a link to a Reddit tutorial). It'll be more easy if you have a PC (preferably a Windows one) so you could do this:
> > > > > 
> > > > > 1. Use the tuto to grab the save files
> > > > > 2. Use a script to convert the Apple (iOS/MacOS) savefile to a Windows/Android savefile (I can do the script for you if needed)
> > > > > 3. Load the savefile in GD on Windows
> > > > > 4. Use GDHM or Geode mods to have verify hack and logout hack
> > > > > 5. Use logout hack to logout without losing data and login to your new account
> > > > > 6. Use verify hack to upload unverified levels
> > > > > 
> > > > > If you don't have a Windows PC, that's gonna be complicated. I can still help you, but honestly I don't read GitHub issues often, so I recommend you to join my Discord server and DM me (DM "{Owner} HGStyle"): https://dsc.gg/hgstyle
> > > > 
> > > > 
> > > > I do have a windows and in fact this comment was posted with my windows, but i do not have a copy of gd on my windows or a steam account.
> > > 
> > > 
> > > Okay, then just use a crack of Geometry Dash. That would be okay to use a crack just for data recovery :) If you need a good crack, go to SteamUnlocked's website and search Geometry Dash. (Use an AdBlocker as there's many ads on the download websites, althought it's possible without an AdBlocker it's just a bit harder)
> > 
> > 
> > okay. also why hasn't steamunlocked been dmcaed yet?
> 
> No idea, but it's probably like asking why isn't The Pirate Bay not dead yet, after dozens of years of service... SteamUblnlocked has been providing GD cracks since 1.9 but they're still here, standing strong...

ok

**Comment by HGStyle** [comment]
Closing as completed, reopen/recomment (and ping me) if needed.

**Comment by ImmediateMurderProfessionals** [comment]
ok

**Comment by ImmediateMurderProfessionals** [comment]
do u have a discord acc

**Comment by HGStyle** [comment]
> do u have a discord acc

https://dsc.gg/hgstyle

**Comment by ImmediateMurderProfessionals** [comment]
> > do u have a discord acc
> 
> https://dsc.gg/hgstyle

ok. I'm @bombcraft on discord.
